service: sql-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  handlerGet:
    handler: handlerGet.get
    events:
      - httpApi:
          method: get
          path: /mensaje
